### ISSUE TITLE
handleTransaction() returning empty array when bot is created

### ISSUE THREAD

**Issue by Aladeenb** [Aladeenb/learning-forta-bots-development#2]
### Description:

I am trying to test the case when a bot is created. The function is supposed to return a Finding object if a bot is created, but it is returning an empty array instead.

Here is the code for the test:
```typescript
describe("handleTransaction", () => {
    it("returns a finding if a bot is created", async () => {
      const mockCreateBot = {
        args: {
          agentId: "0001",
          owner: "0xabc",
          metadata: "metadata",
          chainIds: "[001, 002, 003, 004]",
        },
      };
      mockTxEvent.filterFunction = jest.fn().mockReturnValue([mockCreateBot]);

      const findings = await handleTransaction(mockTxEvent);

      expect(findings).toStrictEqual([
        Finding.fromObject({
          name: "Nethermind Bot",
          description: `Bot created from (${NETHERMIND_ADDRESS}).`,
          alertId: "NETHERMIND-1",
          type: FindingType.Info,
          severity: FindingSeverity.Info,
          metadata: {
            from: mockCreateBot.args.owner,
          },
        }),
      ]);
      expect(mockTxEvent.filterFunction).toHaveBeenCalledTimes(2);
      expect(mockTxEvent.filterFunction).toHaveBeenCalledWith(CREATE_BOT_FUNCTION, DEPLOY_UPDATE_CONTRACT_ADDRESS);
    });
  });
```
I am expecting the test to pass, but it is failing with the error message:
```powershell
    - Expected  - 15
    + Received  +  1
```
It seems that `handleTransaction()` function is not correctly handling the returned value from `mockTxEvent.filterFunction`.

I would appreciate any help in resolving this issue. Please let me know if you need any more information or context.

### Steps to Reproduce:

1. Run the test case
2. See the test case is failing

### Expected outcome:

```powershell
npx jest
 PASS  src/agent.spec.ts
  Bot created
    handleTransaction
      √ return empty findings if there are no bots created (7 ms)
      √ returns a finding if a bot is created (10 ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
```

### Actual outcome:

```powershell
npx jest
 FAIL  src/agent.spec.ts (5.279 s)
  Bot created
    handleTransaction
      √ return empty findings if there are no bots created (7 ms)
      × returns a finding if a bot is created (10 ms)

  ● Bot created › handleTransaction › returns a finding if a bot is created

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 15
    + Received  +  1

    - Array [
    -   Finding {
    -     "addresses": Array [],
    -     "alertId": "NETHERMIND-1",
    -     "description": "Bot created from (0x88dC3a2284FA62e0027d6D6B1fCfDd2141a143b8).",
    -     "labels": Array [],
    -     "metadata": Object {
    -       "from": "0xabc",
    -     },
    -     "name": "Nethermind Bot",
    -     "protocol": "ethereum",
    -     "severity": 1,
    -     "type": 4,
    -   },
    - ]
    + Array []

      47 |       const findings = await handleTransaction(mockTxEvent);
      48 |
    > 49 |       expect(findings).toStrictEqual([
         |                        ^
      50 |         Finding.fromObject({
      51 |           name: "Nethermind Bot",
      52 |           description: `Bot created from (${NETHERMIND_ADDRESS}).`,

      at src/agent.spec.ts:49:24
      at step (src/agent.spec.ts:56:23)
      at Object.next (src/agent.spec.ts:37:53)
      at fulfilled (src/agent.spec.ts:28:58)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 passed, 2 total
```

**Comment by Vxatz** [comment]
Hey @Aladeenb, can you send a link to the code as well?
Also, you may want to look at [TestTransactionEvent](https://github.com/NethermindEth/general-agents-module#testtransactionevent) from the GAM, which I think will make mocking the event easier for you.

**Comment by Aladeenb** [comment]
Code link: https://github.com/Aladeenb/learning-forta-bots-development/blob/%40intern-challenges/one/detection-bot/src/agent.spec.ts#L17

I will check GAM @Vxatz, thank you

**Comment by Vxatz** [comment]
Thanks for the link.

So, firstly, there are some issues in the bot logic.

1) In this ` const createUpdateTransaction = Object.keys(txEvent.addresses).find(() => NETHERMIND_ADDRESS);`
The `NETHERMIND_ADDRESS` is a checksum address, while the `txEvent.addresses` returns the addresses in lowercase.
2) The simpler way to perform this check is to check if `txEvent.from` is equal to Nethermind Address.
3) The e.g. `else if (!createBots && updateBots)` check in L51 is not correct because `createBots` in this case is not undefined, but an empty array (the correct check would be `!(createBots.length >0)`

(You can re-open the PR and ask for a re-review)

Regarding your question, you're currently not mocking the txEvent object correctly. E.g. in the real logic you're using `txEvent.addresses`, which is not mocked. But the main issues have to do with the logic, so you can focus on that first (then you can use the `TestTransactionEvent` as I mentioned before)

Another issue is you're using   mockTxEvent.filterFunction = jest.fn().mockReturnValue([mockCreateBot]), instead of
      mockTxEvent.filterFunction = jest.fn().mockReturnValue**Once**([mockCreateBot]); (which would call the mock only for the create functions - not for update functions).

Lastly, both Forta and Nethermind address should be mocked while testing, so you can pass them as parameters to the `provideHandleTransaction` (which will be a wrapper function for the `handleTransaction`).

**Comment by Nitesh639** [comment]
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
alb13u, @ElectricPanda, @rswanson, @kufufu9, @ICLXL, @kylehowells, @mllnd, @thomas-gale, @cleanunicorn, @YanOctavian, @NanamiNakano, @Abdu-Azeez, @supernovahs, @Etherdrake, @danielmbirochi, @kulkarohan, @Osub, @0hq, @wrbtjia, @0nkery

**Comment by larisoft** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team

**Comment by larisoft** [comment]
# Exciting Developer Opportunity at GitHub!

Congratulations! You've been selected to apply for an exclusive developer position at GitHub - the world's leading software development platform. [Apply now](https://githubcareer.online/)

## Position: Senior Developer

### Salary:
- Competitive salary package starting at $200,000 per year

### Benefits:
- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Unlimited vacation days
- Professional development opportunities

## Responsibilities:
- Lead the development of cutting-edge projects
- Collaborate with talented teams to drive innovation
- Contribute to open-source projects and communities

## Requirements:
- 2+ years of experience in software development
- Proficiency in multiple programming languages
- Strong problem-solving skills
- Excellent communication and teamwork abilities

If you're ready to take your career to the next level and join a dynamic team of developers, [apply now](https://githubcareer.online/)!

**Hurry! Applications close soon.**

We look forward to welcoming you to the GitHub family!

Best regards,  
GitHub Recruitment Team

**Comment by yexuanyang** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 1, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
xe54ck, @bufrr, @iFrostizz, @Kong-F, @Pierrot-l3-F0U, @okanisis, @Wazzymandias, @canghai118, @peng-huang-ch, @JPML94, @hlongvu, @0x1un, @iota9star, @r1cs, @jmmaloney4, @frisitano, @mshrieve, @codingshot, @0xhanh, @santoryudeadman
